services:
  api:
    build:
      context: .
      target: api
    image: gmod-integration/api:local
    env_file:
      - .env
    environment:
      DEV: ${DEV:-false}
      MARIA_HOST: mariadb
      MARIA_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BULLMQ_HOST: redis
      BULLMQ_PORT: 6379
      MONGO_URI: mongodb://mongo:27017
      MINIO_ENDPOINT: http://minio:9000
    ports:
      - "53136:53136"
    depends_on:
      - mariadb
      - redis
      - mongo
      - minio

  websocket:
    build:
      context: .
      target: websocket
    image: gmod-integration/websocket:local
    env_file:
      - .env
    environment:
      DEV: ${DEV:-false}
      MARIA_HOST: mariadb
      MARIA_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BULLMQ_HOST: redis
      BULLMQ_PORT: 6379
      MONGO_URI: mongodb://mongo:27017
      MINIO_ENDPOINT: http://minio:9000
    ports:
      - "53139:53139"
    depends_on:
      - mariadb
      - redis
      - mongo
      - minio

  discord:
    build:
      context: .
      target: discord
    image: gmod-integration/discord:local
    env_file:
      - .env
    environment:
      DEV: ${DEV:-false}
      MARIA_HOST: mariadb
      MARIA_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BULLMQ_HOST: redis
      BULLMQ_PORT: 6379
      MONGO_URI: mongodb://mongo:27017
      MINIO_ENDPOINT: http://minio:9000
    depends_on:
      - mariadb
      - redis
      - mongo
      - minio
