import { defineConfig } from 'vitest/config'

// Root orchestration config: discovers every app/package project (each has its own
// vitest.config.ts, built from ./vitest.config.base.ts) and runs/reports them as one suite.
// `coverage` is configured here (not in vitest.config.base.ts) because it is a root-only
// option in Vitest's projects mode — see docs/reports/ (test coverage plan) for the phased
// rollout and why 100% coverage thresholds are added per-project as each phase lands, not here.
export default defineConfig({
  test: {
    passWithNoTests: true,
    projects: ['apps/*', 'packages/*'],
    coverage: {
      provider: 'v8',
      all: true,
      reporter: ['text', 'html', 'lcov'],
      include: ['apps/*/src/**/*.{ts,tsx}', 'packages/*/src/**/*.{ts,tsx}'],
      exclude: [
        // Vendor output regenerated by `prisma generate` — not project code, see the
        // Phase-0 test-implementation plan for why this is the one intentional exclusion
        // from the "100%, no exclusions" coverage target.
        '**/generated/**',
        '**/*.d.ts',
        '**/dist/**',
        '**/node_modules/**',
        '**/*.config.{ts,js}',
      ],
    },
  },
})
