import { defineConfig } from 'vitest/config'

// Root orchestration config: discovers every app/package project (each has its own
// vitest.config.ts, built from ./vitest.config.base.ts) and runs/reports them as one suite.
// `coverage` is configured here (not in vitest.config.base.ts) because it is a root-only
// option in Vitest's projects mode — see docs/reports/ (test coverage plan) for the phased
// rollout and why 100% coverage thresholds are added per-project as each phase lands, not here.
export default defineConfig({
  test: {
    passWithNoTests: true,
    projects: ['apps/*', 'packages/*'],
    coverage: {
      provider: 'v8',
      all: true,
      reporter: ['text', 'html', 'lcov'],
      include: ['apps/*/src/**/*.{ts,tsx}', 'packages/*/src/**/*.{ts,tsx}'],
      exclude: [
        // Vendor output regenerated by `prisma generate` — not project code, see the
        // Phase-0 test-implementation plan for why this is the one intentional exclusion
        // from the "100%, no exclusions" coverage target.
        '**/generated/**',
        '**/*.d.ts',
        '**/dist/**',
        '**/node_modules/**',
        '**/*.config.{ts,js}',
      ],
      // `thresholds` (like the rest of `coverage`) is a root-only option in Vitest's projects
      // mode, so per-package gates live here, not in each package's own vitest.config.ts.
      // One glob entry gets added per package/app as its test-implementation phase lands
      // (the ratchet from the Phase-0 plan) — see docs/reports/ for the phase list.
      thresholds: {
        'packages/schema/src/**': { statements: 100, branches: 100, functions: 100, lines: 100 },
      },
    },
  },
})
