name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull repository and deploy
        env:
          NODE_ENV: production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          export PATH=$(nvm which current | xargs dirname):$PATH 
          cd ${{ vars.DEPLOY_PATH }}
          git fetch --all
          git reset --hard origin/main
          git pull
          npm install
          npm run build
          npx prisma migrate deploy
          pm2 restart gmod-integration-api
          EOF
